In [22]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import math
import pickle #dump or save your model
from joblib import dump,load 

In [2]:
data_frame = pd.read_csv('HiringProcessNaN.csv')
data_frame
data_frame.columns

Index(['Test score ', 'IQ test score', 'English score', 'Interview score',
       'Years of experiences', 'Salary($) per month'],
      dtype='object')

In [3]:
for key, value in (data_frame.isna().any()).items():
    if value == True:
        print(key,': ',value)

Test score  :  True
English score :  True
Years of experiences :  True


In [4]:
data_frame

Test score   IQ test score  English score  Interview score  \
0           3.0              9            8.0                7   
1           4.0              8           10.0               10   
2           5.0              5            5.0                6   
3           6.0              6            7.0                8   
4          10.0             10           10.0               10   
5           8.0              9           10.0                9   
6           NaN              7            9.0                8   
7           4.0              4            5.0                7   
8           6.0              7            NaN                6   
9           7.0              6            6.0                5   
10          4.0              7            5.0                6   
11          5.0              7            6.0                7   
12          8.0              7            8.0                7   
13          7.0              7            7.0                7   
14          9.0              9            4.0                4   

    Years of experiences  Salary($) per month  
0                    1.0                 2300  
1                    3.0                 5000  
2                    2.0                 2400  
3                    2.0                 2500  
4                    2.0                 7000  
5                    NaN                 6500  
6                    2.0                 6200  
7                    2.0                 2100  
8                    3.0                 4000  
9                    2.0                 2700  
10                   1.0                 2400  
11                   2.0                 2500  
12                   2.0                 5600  
13                   1.0                 5400  
14                   2.0                 5000

In [5]:
import math
test_score_median = data_frame['Test score '].median()
english_score_median = data_frame['English score'].median()
years_of_experiences_median = data_frame['Years of experiences'].median()
test_score_median,english_score_median, years_of_experiences_median
#median != medium

(6.0, 7.0, 2.0)

In [6]:
data_frame['Test score '] = data_frame['Test score '].fillna(test_score_median)
data_frame['English score'] = data_frame['English score'].fillna(english_score_median)
data_frame['Years of experiences'] = data_frame['Years of experiences'].fillna(years_of_experiences_median)

In [7]:
data_frame

Test score   IQ test score  English score  Interview score  \
0           3.0              9            8.0                7   
1           4.0              8           10.0               10   
2           5.0              5            5.0                6   
3           6.0              6            7.0                8   
4          10.0             10           10.0               10   
5           8.0              9           10.0                9   
6           6.0              7            9.0                8   
7           4.0              4            5.0                7   
8           6.0              7            7.0                6   
9           7.0              6            6.0                5   
10          4.0              7            5.0                6   
11          5.0              7            6.0                7   
12          8.0              7            8.0                7   
13          7.0              7            7.0                7   
14          9.0              9            4.0                4   

    Years of experiences  Salary($) per month  
0                    1.0                 2300  
1                    3.0                 5000  
2                    2.0                 2400  
3                    2.0                 2500  
4                    2.0                 7000  
5                    2.0                 6500  
6                    2.0                 6200  
7                    2.0                 2100  
8                    3.0                 4000  
9                    2.0                 2700  
10                   1.0                 2400  
11                   2.0                 2500  
12                   2.0                 5600  
13                   1.0                 5400  
14                   2.0                 5000

In [8]:
linear_regression = linear_model.LinearRegression()
#train the model
linear_regression.fit(
    #features = input = independent values
    data_frame[['Test score ', 'IQ test score', 'English score', 'Interview score',
       'Years of experiences']], 
    #label = output = dependent values
    data_frame['Salary($) per month']
)

LinearRegression()

In [9]:
#where is matplotlib ? NO!
w = linear_regression.coef_
b = linear_regression.intercept_
w, b

(array([497.72837149,  92.42236953, 481.39962075, -36.24526436,
         28.89880385]),
 -2842.8138354546836)

In [15]:
#create a new file and save
#wb = write binary
#save model to file
file_name = 'HiringProcessModel'
with open(file_name, 'wb') as file:
    pickle.dump(linear_regression, file)

In [17]:
#load model from file
#rb = read binary
with open(file_name, 'rb') as file:
    linear_regression2 = pickle.load(file)

In [10]:
linear_regression.predict([[5, 6, 7, 8, 1]])

C:\Users\sunli\.conda\envs\machineLearningTutorial\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([3309.0962734])

In [18]:
linear_regression2.predict([[5, 6, 7, 8, 1]])

C:\Users\sunli\.conda\envs\machineLearningTutorial\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([3309.0962734])

In [11]:
b + 497.7283714*5 + 92.42236953*6 + 481.39962075*7 -36.24526436*8 + 28.89880385 * 1

3309.0962729453163

In [24]:
dump(linear_regression, file_name)

['HiringProcessModel']

In [12]:
b + np.dot(w, [5, 6, 7, 8, 1])

3309.0962734015247

In [25]:
linear_regression3 = load(file_name)
linear_regression3.predict([[5, 6, 7, 8, 1]])

C:\Users\sunli\.conda\envs\machineLearningTutorial\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([3309.0962734])

In [13]:
#what is the problem if some values is NaN(Not a Number)